angular.module('robotStore.Constants', [])
    .constant('names', [
        'Adam Baum',
        'Adam Zapel',
        'Al Bino',
        'Al Dente',
        'Al Fresco',
        'Al K. Seltzer',
        'Alf A. Romeo',
        'Ali Gaither',
        'Ali Katt',
        'Amanda Lay',
        'Rocky Rhoades',
        'Rod N. Reel',
        'Roman Holiday',
        'Rose Bush',
        'Rowan Boatman',
        'Royal Payne',
        'Russell Leeves',
        'Russell Sprout',
        'Rusty Blades, ',
        'Rusty Bridges, ',
        'Rusty Carr, ',
        'Rusty Dorr, ',
        'Rusty Fossat, ',
        'Rusty Fender',
        'Rusty Irons',
        'Rusty Keyes',
        'Rusty Nail',
        'Rusty Pipes',
        'Rusty Steele',
        'Ryan Carnation',
        'Ryan Coke',
        'Sal A. Mander',
        'Sal Minella',
        'Sally Forth',
        'Sarah Bellum',
        'Sawyer B. Hind',
        'Sandy Banks',
        'Seth Poole',
        'Seymour Bush',
        'Shanda Lear',
        'Sharon Fillerup',
        'Sharon Needles',
        'Sheila Blige',
        'Skip Roper',
        'Sonny Day',
        'Sno White',
        'Stan Still',
        'Stanley Cupp',
        'Dr. Steven Sumey',
        'Sue Flay',
        'Sue Ridge',
        'Sue Yu, Sue Jeu',
        'Summer Camp',
        'Sy Burnette',
        'Tad Moore',
        'Tad Pohl',
        'Tanya Hyde',
        'Tara Cherry',
        'Ted E. Baer',
        'Terry Achey',
        'Terry Bull ',
        'Tess Steckle',
        'Therese R. Green',
        'Thomas Richard Harry',
        'Tim Burr',
        'Tish Hughes',
        'Tittsworth & Grabbe',
        'Tom A. Toe',
        'Tom Katt',
        'Tom Morrow',
        'Tommy Gunn',
        'Tommy Hawk',
        'Trina Woods, Trina Forest',
        'Ty Coon, Ty Knotts',
        'Urich Hunt',
        'Viola Solo',
        'Virginia Beach',
        'Walter Melon',
        'Wanda Rinn',
        'Wanna Hickey',
        'Warren Peace',
        'Warren T.',
        'Will Power',
        'Will Race',
        'Will Wynn',
        'Willie B. Hardigan',
        'Willie Stroker',
        'Willie Waite',
        'Winsom Cash, Owen Cash',
        'Woody Forrest',
        'X. Benedict'
    ]);
